f = open('grafana/dashboards/jira-health.json', 'r', encoding='utf-8')
c = f.read()
f.close()
c = c.replace('"type": "PBFA97CFB590B2093"', '"type": "prometheus"')
c = c.replace('${DS_PROMETHEUS}', 'PBFA97CFB590B2093')
f = open('grafana/dashboards/jira-health.json', 'w', encoding='utf-8')
f.write(c)
f.close()
print('done')